### ISSUE TITLE
RecursionError: Caught RecursionError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by lgl603** [OpenFirework/pytorch_solov2#1]
RecursionError: Caught RecursionError in DataLoader worker process 0.

RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by ABlueLight** [comment]
I didn't have that problem. I'll find out what the problem is. @lgl603

**Comment by ABlueLight** [comment]
@lgl603  @Wilbur529  @lhm96  I'm Sorry for this bug~ There is a bug in the data loading part in "data/piplines.py". Now, it's work normally。

I will modify this code for more easier to use.
