### ISSUE TITLE
请问作者：1，您在coco数据集上从0训练是和官方map差不多吗？2，您在自己的机器上训练map只有2.8吗？3，您评估map的代码是使用这里面的评估代码吗？

### ISSUE THREAD

**Issue by seekerwmy** [OpenFirework/pytorch_solov2#19]

**Comment by ABlueLight** [comment]
这个代码不支持多卡训练，感觉哪里应该有点问题，不推荐用这个训练，直接官方的代码训练还是比较舒服的。
1. 是的，但是背景是，设置的batchsize比较大的情况下，我用公司的开发机训练过，精度和官方的差不多，但是还是会低一些，低了0.3~0.5左右吧，具体记不清了。
2. 自己的机器上gpu比较差，map只训练到了2.8
3. 是的

**Comment by ABlueLight** [comment]
可以直接基于本仓库提供的权重文件进行初始化，再训练自己的数据。

**Comment by seekerwmy** [comment]
感谢您的回答，请问您的batchsize比较大设置的是多少？我自己训练的map也是只有2点多？也进行了初始化

**Comment by ABlueLight** [comment]
@seekerwmy 不好意思，好久没弄了，好像是12，有点记不清楚了。这个初始化，可以基于已经训练好的coco权重文件初试化，例如：[solov2_448_r18_epoch_36.pth](https://github.com/OpenFirework/pytorch_solov2/blob/master/pretrained/solov2_448_r18_epoch_36.pth)
相当于已经预训练了。
如果只基于resnet18权重文件初始化，可能效果不好，本质上还是训练的代码或者策略哪里有问题。不推荐用我的这个训练。solov2现在应该也有比较多的实现了，可以参考一下。
