### ISSUE TITLE
mmcv dataloader 报错

### ISSUE THREAD

**Issue by Wilbur529** [OpenFirework/pytorch_solov2#2]
Hi，我修改完coco dataset路径后，启动训练时报这样的错

**Comment by Wilbur529** [comment]
![Uploading image.png…]()

**Comment by Wilbur529** [comment]
定位到了mmcv 的 collate，想问下您有遇到过类似问题吗？

**Comment by Wilbur529** [comment]
File "/envs/conda/envs/wb_exp/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 78, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/envs/conda/envs/wb_exp/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 78, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/envs/conda/envs/wb_exp/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 23, in collate
    if not isinstance(batch, collections.Sequence):
  File "/envs/conda/envs/wb_exp/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
  File "/envs/conda/envs/wb_exp/lib/python3.7/abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
RecursionError: maximum recursion depth exceeded

**Comment by ABlueLight** [comment]
我没遇到，我排查下问题哈，找到问题了会在这下面回复的

**Comment by ABlueLight** [comment]
@Wilbur529

**Comment by ABlueLight** [comment]
> 定位到了mmcv 的 collate，想问下您有遇到过类似问题吗？

你用的mmcv是那个版本，我用的mmcv-full   1.1.6。
我再排查一下

**Comment by Wilbur529** [comment]
> > 定位到了mmcv 的 collate，想问下您有遇到过类似问题吗？
> 
> 你用的mmcv是那个版本，我用的mmcv-full 1.1.6。
> 我再排查一下

@ABlueLight 我用的是0.2.16，那我升级一下再试试，谢了哈

**Comment by lhm96** [comment]
您好，我也遇到了和@Wilbur529同样的问题，定位到mmcv的collate,然后报错RecursionError: maximum recursion depth exceeded in comparison。我用的mmcv版本还有cuda，pytorch都和您readme上的对应了。但是还是报错了。我可能是config写的不对。请问博主可以共享一个config例子吗。或者这个问题应该如何解决呢

**Comment by ABlueLight** [comment]
@Wilbur529  @lhm96  I'm Sorry for this bug~ There is a bug in the data loading part in "data/piplines.py". Now, it's work normally。

I will modify this code for more easier to use.
