### ISSUE TITLE
按照readme安装还是需要mmcv

### ISSUE THREAD

**Issue by WYQ-Github** [OpenFirework/pytorch_solov2#3]
File "/home/yuqing/桌面/program/pytorch_solov2-master/modules/solov2_head.py", line 4, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'

**Comment by ABlueLight** [comment]
修改了，你再试一下

**Comment by WYQ-Github** [comment]
> 修改了，你再试一下
谢谢作者已经可以了。请问作者没有全连接层的resnet50_nofc.pth可以在哪下载呢？

**Comment by ABlueLight** [comment]
这个可以自己制作，很好弄的，我有时间了弄一个传上楼来吧。

**Comment by ABlueLight** [comment]
@WYQ-Github 
resnet50_nofc.pth的下载地址：
https://drive.google.com/file/d/1404SS3ZCpfSaq_-YDHqLZPH-yz9zhmjS/view?usp=sharing

或者：
链接：https://pan.baidu.com/s/1ceewn5W_4YqaQlkgxTPtew 
提取码：1avx
