### ISSUE TITLE
mAP相关

### ISSUE THREAD

**Issue by pangkun248** [OpenFirework/pytorch_solov2#4]
您好，请问这份代码能否达到mmd版本的训练精度呢。或者说和官方版本有什么差别吗？

**Comment by ABlueLight** [comment]
这份代码就是从mmd里面的代码抠出来的，训练速度，分布式训练肯定没有mmd做的好，训练精度是基本可以达到的，差距非常小，因为和官方的代码完全一致。我做这个只是为了方便理解solov2的各个结构，方便修改各个模块的代码，没有其他功能模块的修改。也考虑到以后基于这份代码导出onnx，然后做一个移动端部署或者trt部署啥的。

**Comment by ABlueLight** [comment]
我从零训练过coco数据集，分割精度基本一致，这个不用担心，因为代码是完全一样的，就是我的不支持多卡训练，batchsize大小有影响，精度可能差一点点，不过如果batchsize 设置12以上，训练的精度基本差不多。

**Comment by pangkun248** [comment]
好的，感谢你分享的代码。
