### ISSUE TITLE
请问COCO_LABEL_MAP是干什么用的呢

### ISSUE THREAD

**Issue by xiezhiyu275** [OpenFirework/pytorch_solov2#6]
谢谢作者，我用自己的数据集跑通了，就是有点不太明白config.py中的COCO_LABEL_MAP是干什么用的，还有就是作者最后损失降到了多少呢

**Comment by ABlueLight** [comment]
coco数据集中的标签并非1-80连续的标签，这个COCO_LABEL_MAP是讲实际coco数据集中的标签，映射到1-80连续的数字标签。损失的话，有点网络，我有时间再看一下，最后损失降到了多少。

**Comment by xiezhiyu275** [comment]
好的，谢谢啦，还有就是请问coco数据集上最后跑得结果怎么样呢，我在我自己得数据集上最后的结果不是很好，想问问有什么可以改进的呢，有20%的漏报，我的正样本只有一个类别，初始损失3.5，最后损失0.6，用sgd损失波动比较大，我就用的adam

**Comment by ABlueLight** [comment]
我在COCO数据集上的训练精度，使用Resnet34作为主干网络，最后mAP可以达到32点多，和原始的solov2差不多的精度；如果在你的数据集上表现不好的话，是不是数据集难，使用大一点的网络，用一些数据增强啥的，没有什么好的改进方法... 自己可以看看solo v2的论文，看有没有可以提高的点... 加油！
